### ISSUE TITLE
Give better iframe embedding example

### ISSUE THREAD

**Issue by austingayler** [winds-mobi/winds-mobi-client-js#7]
https://github.com/winds-mobi/winds-mobi-client-js/blob/dc78ca0b8d6a0c51b1c0c8a81bd29c690ea943e0/src/html/templates/help.html#L125

I suggest this could be changed to:
```
        <iframe
          allow="geolocation"
          src="https://winds.mobi/stations/list?lat=46.6833&lon=7.8500&zoom=15"
        />
```

Just as a more complete code example, and because without the `allow="geolocation"` line, the embedded iframe won't have access to the user's location, so the map view is wrong. 

Relevant SO issue:
https://stackoverflow.com/questions/64582203/how-do-i-allow-the-geolocation-api-inside-an-iframe

**Comment by ysavary** [comment]
Thank you for reporting 👍

I just did a small fix:
![Screenshot 2024-07-06 at 16 16 45](https://github.com/winds-mobi/winds-mobi-client-js/assets/600094/a09bc6f9-bccf-460d-ba1f-7addabcaeca0)
